services:
  # app:
  #   build:
  #     context: .
  #   image: nextjs-dev
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     NODE_ENV: development
  #   develop:
  #     watch: #run with --watch flag
  #       - action: sync
  #         path: ./src
  #         target: /app/src
  #         ignore:
  #           - node_modules
  #       - action: rebuild
  #         path: package.json
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
